str = "I like to stay in the surroundings of nature."
print(str[1])
print(str[2])
print(str[3])
print(str[4])
print(str[5])
print(str[6 : 10])
print(str[11 : 13])
print(str[13-20])
print(str[-1])
print(str[-2])
print(str[: 19])
print(str[: 20])
print(str[4:])
print(str[-10])
print(str[-34])
print(str[-3:])
print(str[45:])
print(str[-45:])