marks = [98, 88.5, 90, 78, 65, 61, 92, 58, 56, 32, 54, 42]
print(marks)
print(type(marks))
print(len(marks))
print(marks[0])
print(marks[6])
print(marks[-1])
print(marks[-8])
print(marks[1:6])
print(marks[:7])
print(marks[4:])
print(marks[-3:-9])
print(marks[:])
print(marks[-4:-1])
print(marks[:-1])
print(marks[-4:])
marks[4] = 75
print(marks)
marks[-3] = 100
print(marks)
marks.append(44)
print(marks)
marks.sort()
print(marks)
marks.sort(reverse = True)
print(marks)
marks.reverse()
print(marks)
marks.insert(1 , 99)
print(marks)
marks.remove(100)
print(marks)
marks.pop(2)
print(marks)