seq = range(1, 101, 1)
print(seq)
print(seq[0])
print(seq[1])
print(seq[2])
print(seq[3])
print(seq[4])
print(seq[-1])
print(seq[1:5])
print(seq[:5])
print(seq[1:])
print(seq[:])
print(seq[-1:])
print(seq[:-5])
print(seq[-2 :-3])
print(type(seq))
print(len(seq))

for i in seq :
    print(i)
    print(type(i))

seq2 = range(100, 0,- 1)
print(seq2)
print(seq2[0])
print(seq2[1])
print(seq2[2])
print(seq2[3])
print(seq2[4])
print(seq2[-1])
print(seq2[1:5])
print(seq2[:5])
print(seq2[1:])
print(seq2[:])
print(seq2[-1:])
print(seq2[:-5])
print(seq2[-2 :-3])
print(type(seq2))
print(len(seq2))

for i2 in seq2 :
    print(i2)
    print(type(i2))

n= int(input("ENTER THE NUMBER :"))
seq3 = range(1,11,1)
for i3 in seq:
    print(n * i3)
    print(seq3)
    print(seq3[0])
    print(seq3[1])
    print(seq3[2])
    print(seq3[3])
    print(seq3[4])
    print(seq3[-1])
    print(seq3[1:5])
    print(seq3[:5])
    print(seq3[1:])
    print(seq3[:])
    print(seq3[-1:])
    print(seq3[:-5])
    print(seq3[-2:-3])
    print(type(seq3))
    print(len(seq3))
    print(type(i3))