f = open("study.txt", "a")
f.close()
f= open("study.txt", "w")
f.write("\nAfter passing HSC or graduating from my school after passing 12 th grade I will apply in some good foreign universities for a software engineering course ")
f.write("\nI will enroll myself in a good university which will offer me scholarship ")
f.close()
f= open("study.txt", "r")
info = f.read()
print(info)
print(len(info))
print(type(info))
print(info[0])
print(info[3])
print(info[-2])
print(info[:4])
print(info[4:])
print(info[2:6])
print(info[-3:])
print(info[:-2])
print(info[-2:-1])
print(info[-2], end ="")
print(info[6], end="")