f = open("demo.txt", "r")
data = f.read()
print(data)
print(type(data))
print(len(data))
print(data[0])
print(data[3])
print(data[-2])
print(data[:4])
print(data[4:])
print(data[2:6])
print(data[-3:])
print(data[:-2])
print(data[-2:-1])
print(data[-2], end ="")
print(data[6], end="")

f = open("demo.txt", "r")
data = f.read(9)
print(data)

print(type(data))
print(len(data))
print(data[0])
print(data[3])
print(data[-2])
print(data[:4])
print(data[4:])
print(data[2:6])
print(data[-3:])
print(data[:-2])
print(data[-2:-1])
print(data[-2], end ="")
print(data[6], end="")

f= open("demo.txt", "r")
data = f.read(-3)
print(data)
print(type(data))
print(len(data))
print(data[0])
print(data[3])
print(data[-2])
print(data[:4])
print(data[4:])
print(data[2:6])
print(data[-3:])
print(data[:-2])
print(data[-2:-1])
print(data[-2], end ="")
print(data[6], end="")

f = open("demo.txt", "r")
line1 = f.readline()
print(line1)
print(type(line1))
print(len(line1))
print(line1[0])
print(line1[3])
print(line1[-2])
print(line1[:4])
print(line1[4:])
print(line1[2:6])
print(line1[-3:])
print(line1[:-2])
print(line1[-2:-1])
print(line1[-2], end ="")
print(line1[6], end="")

f = open("demo.txt", "r")
line1 = f.readline(4)
print(line1)
print(type(line1))
print(len(line1))
print(line1[0])
print(line1[3])
print(line1[-2])
print(line1[:4])
print(line1[4:])
print(line1[2:6])
print(line1[-3:])
print(line1[:-2])
print(line1[-2:-1])
print(line1[-2], end ="")
print(line1[2], end="")

f = open("demo.txt", "r")
line2 = f.readline()
print(line2)
print(type(line2))
print(len(line2))
print(line2[0])
print(line2[3])
print(line2[-2])
print(line2[:4])
print(line2[4:])
print(line2[2:6])
print(line2[-3:])
print(line2[:-2])
print(line2[-2:-1])
print(line2[-2], end ="")
print(line2[6], end="")

f= open("demo.txt", "r")
line2 = f.readline(-3)
print(line2)
print(type(line2))
print(len(line2))
print(line2[0])
print(line2[3])
print(line2[-2])
print(line2[:4])
print(line2[4:])
print(line2[2:6])
print(line2[-3:])
print(line2[:-2])
print(line2[-2:-1])
print(line2[-2], end ="")
print(line2[6], end="")
