names = {"Rimon", "Rishad", "Rimon", "Zarif", "Jawad", "Nabil", "Soptok", "Nill", "Ehan"}
names2 = set()
print(names2)
print(len(names2))
names2.add("Shajnina")
names2.add("Arisha")
names2.add("Jion")
names2.add("Nidhi")
names2.add("Raya")
print(names)
print(names2)
print(type(names))
print(type(names2))
print(len(names))
print(len(names2))
names.add("Zafrin")
print(names)
print(len(names))
names.remove("Zafrin")
print(names)
names2.clear()
print(names2)
print(len(names2))
names.pop()
print(names)
print(len(names))