str = "i like to read story books with a cup of tea in a rainy day in a natural beautiful place"
print(str)
print(str.endswith("lace"))
print(str.endswith("app"))
print(str.capitalize())
str = str.capitalize()
print(str.replace("a", "s"))
print(str.replace("tea", "coffee"))
print(str.count("o"))
print(str.count("q"))
print(str.count("read"))
print(str.count("eat"))
print(str.find("e"))
print(str.find("q"))
print(str.find("beautiful"))
print(str.find("eat"))