with open("age.txt", "r") as f:
    info =f.read()
    print(info)
print(len(info))
print(type(info))
print(info[0])
print(info[3])
print(info[-2])
print(info[:4])
print(info[4:])
print(info[2:6])
print(info[-3:])
print(info[:-2])
print(info[-2:-1])
print(info[-2], end ="")
print(info[6], end="")


with open("age.txt", "r") as f:
    line1 = f.readline()
    print(line1)
    print(len(line1))
    print(type(line1))
    print(line1[0])
    print(line1[3])
    print(line1[-2])
    print(line1[:4])
    print(line1[4:])
    print(line1[2:6])
    print(line1[-3:])
    print(line1[:-2])
    print(line1[-2:-1])
    print(line1[-2], end="")
    print(line1[6], end="")

    with open("age.txt", "r") as f:
        line2 = f.readline(-2)
        print(line2)
        print(len(line2))
        print(type(line2))
        print(line2[0])
        print(line2[3])
        print(line2[-2])
        print(line2[:4])
        print(line2[4:])
        print(line2[2:6])
        print(line2[-3:])
        print(line2[:-2])
        print(line2[-2:-1])
        print(line2[-2], end="")
        print(line2[6], end="")

with open("colour.txt", "w") as f:
    f.write("MY favourite colours are red and black" "\n")
    f.write("I also like green as it is the colour of nature")
